services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      # 数据文件
      - ./volumes/mongodb/db:/data/db
      # 备份文件
      - ./volumes/mongodb/backup:/data/backup
      # logs 文件
      - ./volumes/mongodb/logs:/data/logs
      # 配置文件
      - ./volumes/mongodb/conf:/etc/mongod.conf
      # init script
      - ./volumes/mongodb/scripts:/docker-entrypoint-initdb.d/
    command: mongod --replSet rs0
    healthcheck:
      test: |
        mongosh --eval "try { rs.status().ok } catch (e) { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'localhost:27017' }] }).ok }"
      start_period: 0s
      interval: 500ms
      timeout: 5s
      retries: 5
    # rs.initiate({"_id": "rs0", "members":[{"_id": 0, "host": "192.168.10.121:27017"}]});
    environment:
      - TZ=Asia/Shanghai
    networks:
      - dev
networks:
  dev:
    name: local-dev